INSERT INTO barrio VALUES(1,'Chacarita',15);
INSERT INTO barrio VALUES(2,'La Paternal',15);
INSERT INTO barrio VALUES(3,'Villa Crespo',15);
INSERT INTO barrio VALUES(4,'Palermo',14);
INSERT INTO barrio VALUES(5,'Villa del Parque',11);
INSERT INTO barrio VALUES(6,'Almagro',5);
INSERT INTO barrio VALUES(7,'La Boca',4);
INSERT INTO barrio VALUES(8,'Belgrano',13);
INSERT INTO barrio VALUES(9,'Villa Pueyrredon',12);
INSERT INTO barrio VALUES(10,'Agronomía',15);
INSERT INTO barrio VALUES(11,'Balvanera',3);
INSERT INTO barrio VALUES(12,'Barracas',4);
INSERT INTO barrio VALUES(13,'Boedo',5);
INSERT INTO barrio VALUES(14,'Constitución',1);
INSERT INTO barrio VALUES(15,'Retiro',1);
INSERT INTO barrio VALUES(16,'San Nicolás',1);
INSERT INTO barrio VALUES(17,'Puerto Madero',1);
INSERT INTO barrio VALUES(18,'San Telmo',1);
INSERT INTO barrio VALUES(19,'Montserrat',1);
INSERT INTO barrio VALUES(20,'Recoleta',2);
INSERT INTO barrio VALUES(21,'San Cristóbal',3);
INSERT INTO barrio VALUES(22,'Nueva Popeya',4);
INSERT INTO barrio VALUES(23,'Parque Patricios',4);
INSERT INTO barrio VALUES(24,'Caballito ',6);
INSERT INTO barrio VALUES(25,'Flores',7);
INSERT INTO barrio VALUES(26,'Parque Chacabuco',7);
INSERT INTO barrio VALUES(27,'Villa Soldati',8);
INSERT INTO barrio VALUES(28,'Villa Riachuelo',8);
INSERT INTO barrio VALUES(29,'Villa Lugano',8);
INSERT INTO barrio VALUES(30,'Liniers',9);
INSERT INTO barrio VALUES(31,'Mataderos',9);
INSERT INTO barrio VALUES(32,'Parque Avellaneda',9);
INSERT INTO barrio VALUES(33,'Villa Real',10);
INSERT INTO barrio VALUES(34,'Monte Castro',10);
INSERT INTO barrio VALUES(35,'Versalles',10);
INSERT INTO barrio VALUES(36,'Floresta',10);
INSERT INTO barrio VALUES(37,'Vélez Sarsfield',10);
INSERT INTO barrio VALUES(38,'Villa Luro',10);
INSERT INTO barrio VALUES(39,'Villa General Mitre',11);
INSERT INTO barrio VALUES(40,'Villa Devoto',11);
INSERT INTO barrio VALUES(41,'Villa Santa Rita',11);
INSERT INTO barrio VALUES(42,'Coghlan',12);
INSERT INTO barrio VALUES(43,'Villa Urquiza',12);
INSERT INTO barrio VALUES(44,'Saavedra',12);
INSERT INTO barrio VALUES(45,'Núñez',13);
INSERT INTO barrio VALUES(46,'Colegiales',13);
INSERT INTO barrio VALUES(47,'Villa Ortúzar',15);
INSERT INTO barrio VALUES(48,'Parque Chas',15);